# Generated by Django 4.1 on 2022-08-17 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('bio', models.TextField(max_length=250, verbose_name='Biografia resumida')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=100, verbose_name='Tags (separe por vírgulas e coloque a principal em primeiro)')),
                ('is_draft', models.BooleanField(default=True, verbose_name='É rascunho?')),
                ('title', models.CharField(max_length=100, verbose_name='Título do post')),
                ('cover', models.URLField(verbose_name='URL da imagem da capa')),
                ('content', models.TextField(max_length=5000, verbose_name='Conteúdo do post')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='Data de publicação')),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Autor')),
            ],
            options={
                'ordering': ('pub_date', 'title'),
            },
        ),
    ]
