# Generated by Django 4.1 on 2022-08-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='stars',
            field=models.CharField(choices=[('✧', '✧'), ('✧✧', '✧✧'), ('✧✧✧', '✧✧✧'), ('✧✧✧✧', '✧✧✧✧'), ('✧✧✧✧✧', '✧✧✧✧✧')], max_length=5, verbose_name='Estrelas'),
        ),
    ]
