# Generated by Django 4.1 on 2022-08-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('simple_description', models.CharField(max_length=5000, verbose_name='Sobre')),
                ('more_description', models.CharField(max_length=5000, verbose_name='Sobre')),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200, verbose_name='Icon')),
                ('name', models.CharField(max_length=250, verbose_name='Nome da competência')),
                ('description', models.TextField(max_length=800, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Iam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello_msg', models.CharField(max_length=100, verbose_name='Mensagem de boas vindas')),
                ('name', models.CharField(max_length=5000, verbose_name='Meu nome')),
                ('featured_skills', models.CharField(max_length=5000, verbose_name='Tags de competências [separe com vírgula]')),
            ],
        ),
    ]
