# Generated by Django 4.1 on 2022-08-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'Sobre'},
        ),
        migrations.AlterModelOptions(
            name='competence',
            options={'verbose_name': 'Competência'},
        ),
        migrations.AlterModelOptions(
            name='iam',
            options={'verbose_name_plural': 'I Am'},
        ),
        migrations.AlterField(
            model_name='about',
            name='more_description',
            field=models.TextField(max_length=5000, verbose_name='Descrição em mais detalhes sobre mim'),
        ),
        migrations.AlterField(
            model_name='about',
            name='simple_description',
            field=models.TextField(max_length=5000, verbose_name='Descrição suscinta sobre mim'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=100, verbose_name="Titulo do 'Sobre'"),
        ),
    ]
