# Generated by Django 4.1 on 2022-08-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_about_options_alter_competence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ('index_order',), 'verbose_name': 'Competência'},
        ),
        migrations.AddField(
            model_name='competence',
            name='index_order',
            field=models.IntegerField(default=0, max_length=2, verbose_name='Ordem de exibição'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='icon',
            field=models.CharField(max_length=200, verbose_name='Icon class (ex: Font Awesome)'),
        ),
    ]
