# Generated by Django 4.1 on 2022-08-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_competence_options_competence_index_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='description',
            field=models.TextField(max_length=119, verbose_name='Descrição'),
        ),
    ]
