# Generated by Django 4.1 on 2022-08-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_competence_description_alter_competence_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do cargo')),
                ('where', models.CharField(max_length=250, verbose_name='Local trabalho')),
                ('when', models.CharField(max_length=50, verbose_name='Quando [Ano-Inicio - Ano-Fim]')),
                ('description', models.TextField(max_length=85, verbose_name='Descrição do cargo')),
            ],
            options={
                'verbose_name': 'Competência',
                'ordering': ('-when',),
            },
        ),
        migrations.AlterField(
            model_name='competence',
            name='index_order',
            field=models.IntegerField(default=0, verbose_name='Ordem de exibição'),
        ),
    ]
