# Generated by Django 4.1 on 2022-08-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_experience_alter_competence_index_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=50, verbose_name='Quem premiou/reconheceu')),
                ('description', models.TextField(max_length=250, verbose_name='Descrição do prêmio')),
                ('link', models.URLField(verbose_name='Link para prova da premiação/reconhecimento')),
            ],
            options={
                'verbose_name': 'Reconhecimento',
                'ordering': ('who',),
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-when',), 'verbose_name': 'Experiência'},
        ),
    ]
