# Generated by Django 4.1 on 2022-08-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_award_alter_experience_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ('index_order',), 'verbose_name': 'Reconhecimento'},
        ),
        migrations.AddField(
            model_name='award',
            name='index_order',
            field=models.IntegerField(default=0, verbose_name='Ordem de exibição'),
        ),
    ]
