# Generated by Django 4.1 on 2022-08-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_award_options_award_index_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250, verbose_name='Título da obra/texto')),
                ('abstract', models.TextField(max_length=250, verbose_name='Resumo')),
                ('link', models.URLField(verbose_name='Link da obra /texto')),
                ('index_order', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Papper',
                'ordering': ('index_order',),
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('index_order',), 'verbose_name': 'Experiência'},
        ),
        migrations.AddField(
            model_name='experience',
            name='index_order',
            field=models.IntegerField(default=0, verbose_name='Ordem de exibição'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(max_length=85, verbose_name='Descrição do Cargo ou do Título Acadêmico'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome do Cargo ou do Título Acadêmico'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='where',
            field=models.CharField(max_length=250, verbose_name='Local'),
        ),
    ]
