# Generated by Django 4.1 on 2022-08-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_papper_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papper',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Título da obra/texto'),
        ),
    ]
