# Generated by Django 4.1 on 2022-08-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_papper_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Link da imagem do produto')),
                ('name', models.CharField(max_length=18, verbose_name='Nome do produto')),
                ('product_owner', models.CharField(max_length=200, verbose_name='Demandante')),
                ('description', models.TextField(max_length=300, verbose_name='Descrição do produto desenvolvido')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='Link do github')),
                ('website_link', models.URLField(blank=True, null=True, verbose_name='Link do website')),
                ('index_order', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
        ),
    ]
