# Generated by Django 4.1 on 2022-08-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Descrição do produto desenvolvido'),
        ),
    ]
