# Generated by Django 4.1 on 2022-08-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_portfolioitem_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='video_url',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='video_embed_code',
            field=models.TextField(blank=True, null=True, verbose_name='Código HTML do video incorporado (embedded)'),
        ),
    ]
