# Generated by Django 4.1 on 2022-08-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_portfolioitem_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iam',
            name='address',
            field=models.CharField(default='Rio de Janeiro, Brasil', max_length=750, verbose_name='Endereço profissional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iam',
            name='email',
            field=models.EmailField(default='maycon@barretolopes.com', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iam',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iam',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iam',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iam',
            name='telephone',
            field=models.CharField(default='+55 22 99976-3091', max_length=750, verbose_name='Número de telefone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iam',
            name='tweeter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iam',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
